const ROWS=3,COLS=9,CELLS=27,MAX=3;
const state={editing:true,dark:false,cards:[newCard()],called:[],history:[]};
const el={};
document.addEventListener("DOMContentLoaded",()=>{Object.assign(el,{cardsContainer:document.getElementById("cardsContainer"),numberPad:document.getElementById("numberPad"),editBtn:document.getElementById("editBtn"),addCardBtn:document.getElementById("addCardBtn"),removeCardBtn:document.getElementById("removeCardBtn"),resetBtn:document.getElementById("resetBtn"),undoBtn:document.getElementById("undoBtn"),themeBtn:document.getElementById("themeBtn"),calledCount:document.getElementById("calledCount"),hitCount:document.getElementById("hitCount"),remainingCount:document.getElementById("remainingCount"),toast:document.getElementById("toast")});load();bind();renderAll();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});});
function newCard(){return{cells:Array.from({length:CELLS},()=>({value:"",marked:false}))}}
function bind(){
el.editBtn.onclick=()=>{state.editing=!state.editing;renderAll();save()};
el.addCardBtn.onclick=()=>{if(state.cards.length>=MAX)return toast("Máximo 3 cartones");state.cards.push(newCard());state.editing=true;renderAll();save()};
el.removeCardBtn.onclick=()=>{if(state.cards.length<=1)return toast("Debe quedar un cartón");state.cards.pop();renderAll();save()};
el.resetBtn.onclick=()=>{if(!confirm("¿Reiniciar números y tachados?"))return;state.called=[];state.history=[];state.cards.forEach(c=>c.cells.forEach(x=>x.marked=false));sessionStorage.clear();renderAll();save()};
el.undoBtn.onclick=()=>{const n=state.history.shift();if(!n)return toast("No hay nada que deshacer");state.called=state.called.filter(x=>x!==n);state.cards.forEach(c=>c.cells.forEach(x=>{if(Number(x.value)===n)x.marked=false}));renderAll();save()};
el.themeBtn.onclick=()=>{state.dark=!state.dark;renderAll();save()};
}
function renderAll(){document.body.classList.toggle("dark",state.dark);el.themeBtn.textContent=state.dark?"☀️":"🌙";el.editBtn.textContent=state.editing?"Jugar":"Editar";el.addCardBtn.disabled=state.cards.length>=MAX;el.removeCardBtn.disabled=state.cards.length<=1;renderCards();renderPad();renderStats()}
function renderCards(){el.cardsContainer.innerHTML="";state.cards.forEach((card,ci)=>{const box=document.createElement("div");box.className="card-box";box.innerHTML=`<div class="card-title"><span>Cartón ${ci+1}</span><span class="card-status">${state.editing?"Editando":"En juego"}</span></div>`;const grid=document.createElement("div");grid.className="bingo-grid";card.cells.forEach(cell=>{const d=document.createElement("div");d.className="bingo-cell"+(!cell.value?" empty":"")+(cell.marked&&!state.editing?" marked":"");if(state.editing){const inp=document.createElement("input");inp.type="text";inp.inputMode="numeric";inp.maxLength=2;inp.value=cell.value;inp.oninput=e=>{let v=e.target.value.replace(/\D/g,"").slice(0,2);if(Number(v)>90)v="90";e.target.value=v;cell.value=v;cell.marked=false;renderPad();renderStats();save()};d.appendChild(inp)}else{d.textContent=cell.value;d.onclick=()=>{if(!cell.value)return;cell.marked=!cell.marked;renderAll();save()}}grid.appendChild(d)});box.appendChild(grid);el.cardsContainer.appendChild(box)})}
function renderPad(){el.numberPad.innerHTML="";const vals=new Set(state.cards.flatMap(c=>c.cells.map(x=>Number(x.value)).filter(Boolean)));for(let n=1;n<=90;n++){const b=document.createElement("button");b.className="number-btn"+(state.called.includes(n)?" called":"")+(state.called.includes(n)&&vals.has(n)?" hit":"");b.textContent=n;b.onclick=()=>callNumber(n);el.numberPad.appendChild(b)}}
function callNumber(n){if(!state.called.includes(n)){state.called.unshift(n);state.history.unshift(n)}let hits=0;state.cards.forEach(c=>c.cells.forEach(x=>{if(Number(x.value)===n){if(!x.marked)hits++;x.marked=true}}));if(navigator.vibrate)navigator.vibrate(hits?[120,50,120]:40);renderAll();save();toast(hits?`${n}: marcado en ${hits} cartón${hits===1?"":"es"}`:`${n}: no está en tus cartones`);check()}
function renderStats(){const cells=state.cards.flatMap(c=>c.cells).filter(x=>x.value);el.calledCount.textContent=state.called.length;el.hitCount.textContent=cells.filter(x=>x.marked).length;el.remainingCount.textContent=cells.filter(x=>!x.marked).length}
function check(){state.cards.forEach((c,ci)=>{const filled=c.cells.filter(x=>x.value);if(filled.length>=15&&filled.every(x=>x.marked)){const k=`b${ci}`;if(!sessionStorage.getItem(k)){sessionStorage.setItem(k,"1");toast(`¡BINGO en el cartón ${ci+1}!`)}}for(let r=0;r<ROWS;r++){const row=c.cells.slice(r*COLS,(r+1)*COLS).filter(x=>x.value);const k=`l${ci}-${r}`;if(row.length&&row.every(x=>x.marked)&&!sessionStorage.getItem(k)){sessionStorage.setItem(k,"1");toast(`¡LÍNEA en el cartón ${ci+1}!`)}}})}
function save(){localStorage.setItem("bingogo3",JSON.stringify(state))}
function load(){try{const s=JSON.parse(localStorage.getItem("bingogo3")||"{}");if(Array.isArray(s.cards)&&s.cards.length)state.cards=s.cards.slice(0,MAX);if(Array.isArray(s.called))state.called=s.called;if(Array.isArray(s.history))state.history=s.history;if(typeof s.editing==="boolean")state.editing=s.editing;if(typeof s.dark==="boolean")state.dark=s.dark}catch{}}
function toast(m){el.toast.textContent=m;el.toast.classList.remove("hidden");clearTimeout(window.tt);window.tt=setTimeout(()=>el.toast.classList.add("hidden"),2200)}